/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import chart.ModelChart;
import java.awt.Color;

/**
 *
 * @author YAN
 */
public class Form2 extends javax.swing.JPanel {

    /**
     * Creates new form Form1
     */
    public Form2() {
        initComponents();
        setOpaque(false);
        init();
    }

    private void init() {
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputID1 = new widget.inputID();
        jLabel1 = new javax.swing.JLabel();
        inputName1 = new widget.inputName();
        inputCMND1 = new widget.inputCMND();
        inputDate1 = new widget.inputDate();
        hoursCustom2 = new calendar.HoursCustom();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        add(inputID1);
        inputID1.setBounds(40, 120, 213, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Summary of medical records");
        add(jLabel1);
        jLabel1.setBounds(270, 40, 328, 32);
        add(inputName1);
        inputName1.setBounds(60, 70, 213, 24);
        add(inputCMND1);
        inputCMND1.setBounds(40, 90, 214, 24);
        add(inputDate1);
        inputDate1.setBounds(40, 150, 213, 24);
        add(hoursCustom2);
        hoursCustom2.setBounds(260, 390, 170, 95);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private calendar.HoursCustom hoursCustom2;
    private widget.inputCMND inputCMND1;
    private widget.inputDate inputDate1;
    private widget.inputID inputID1;
    private widget.inputName inputName1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
